name: Multiplatform Build Pipeline

on:
  pull_request:
    branches: ["master"]

jobs:
  build-library-android:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4 # This MUST come first
      - name: Setup
        uses: ./.github/actions/setup-project # Now it can find this file
      - name: Build Library (Android)
        run: ./gradlew :camera:assembleDebug

  build-library-ios:
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup
        uses: ./.github/actions/setup-project
      - name: Build Library (iOS)
        run: ./gradlew :camera:iosSimulatorArm64Binaries

  build-app-android:
    needs: build-library-android
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup
        uses: ./.github/actions/setup-project
      - name: Build App (Android)
        run: ./gradlew :demo:composeApp:assembleDebug

  build-app-ios:
    needs: build-library-ios
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup
        uses: ./.github/actions/setup-project

      - name: Build App (Kotlin + Swift)
        run: |
          xcodebuild -project demo/iosApp/iosApp.xcodeproj \
            -scheme iosApp \
            -configuration Debug \
            -sdk iphonesimulator \
            -destination 'platform=iOS Simulator' \
            build \
            CODE_SIGNING_ALLOWED=NO